### ISSUE TITLE
bgrabitmap

### ISSUE THREAD

**Issue by severak** [afrantzis/pixel-format-guide#2]
some useful info may be in source code of https://github.com/bgrabitmap/bgrabitmap/

see https://github.com/bgrabitmap/bgrabitmap/blob/47628d6de2122dbfe5b26b80ba27e32d1c74435b/bgrabitmap/bgrapixel.inc

**Comment by afrantzis** [comment]
Added BGRABitmap pixel format family in https://github.com/afrantzis/pixel-format-guide/commit/b63dd04333378cf4d8eb30efd117e542fadcebab.
